//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account
    {
        public int id { get; set; }
        public string U_wxaccount { get; set; }
        public string U_UserName { get; set; }
        public string U_PassWord { get; set; }
        public string U_NickName { get; set; }
        public string U_Icon { get; set; }
        public System.DateTime U_RegTime { get; set; }
    }
}
